apiVersion: v1
kind: Service
metadata:
  name: magento2-app
spec:
  type: LoadBalancer
  selector:
    app: magento2-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: magento2-app
